env:
  es6: true
  node: true
  mocha: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  no-use-before-define: 0
  prefer-const: 1
  no-underscore-dangle: [2, allow: ["_id", "__v"]]
  no-unused-vars: [2, argsIgnorePattern: "next"]
  import/extensions: [".js"]